# Generated by Django 2.2 on 2021-12-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilelfeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilelFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
